return {
  {id="capture-assistant", name="Capture Assistant", version="0.1.1", entry="main.lua"},
  {id="daycare-viewer", name="Day Care Viewer", version="0.2.1", entry="main.lua"},
  {id="disable-lr-help", name="Disable L/R Help", version="0.1.0", entry="main.lua"},
  {id="fly-teleport", name="Fly Teleport", version="0.2.2", entry="main.lua"},
  {id="frlg_qol_auto_surf", name="Quick Field Actions", version="0.3.0", entry="main.lua"},
  {id="frlg_qol_bag_sort", name="Sorted Bag", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_ball_shortcut", name="Battle Ball Shortcut", version="0.2.2", entry="main.lua"},
  {id="frlg_qol_battle_pacing", name="Battle Bar Speed", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_berry_restock", name="Held Berry Replacement", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_dex_companion", name="Dex Companion", version="0.1.2", entry="main.lua"},
  {id="frlg_qol_fast_healing", name="Faster Center Healing", version="0.2.0", entry="main.lua"},
  {id="frlg_qol_hm_field_kit", name="HM Field Kit", version="0.2.4", entry="main.lua"},
  {id="frlg_qol_hoenn_tools", name="Hoenn Tools", version="0.1.2", entry="main.lua"},
  {id="frlg_qol_hold_fast_forward", name="Hold Fast Forward", version="0.2.2", entry="main.lua"},
  {id="frlg_qol_instant_text", name="Fast / Instant Text", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_key_item_help", name="Key Item Help", version="0.1.2", entry="main.lua"},
  {id="frlg_qol_map_services", name="Town Map Companion", version="0.1.3", entry="main.lua"},
  {id="frlg_qol_party_items", name="Party Held Items", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_party_nickname", name="Party Nickname", version="0.2.0", entry="main.lua"},
  {id="frlg_qol_party_reminder", name="Party Move Reminder", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_quick_save_prompt", name="Quicker Save Confirmation", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_quiet_exp", name="Quiet EXP", version="0.1.0", entry="main.lua"},
  {id="frlg_qol_repel_reuse", name="Repel Reuse Prompt", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_reusable_tms", name="Reusable TMs", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_running_start", name="Running From Start", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_shop_count", name="Shop Owned Count", version="0.2.0", entry="main.lua"},
  {id="frlg_qol_summary_info", name="Expanded Summary Info", version="0.1.1", entry="main.lua"},
  {id="frlg_qol_vs_seeker_status", name="VS Seeker Readiness", version="0.1.2", entry="main.lua"},
  {id="frlg_scrollable_start", name="Scrollable Start Menu", version="0.3.1", entry="main.lua"},
  {id="pokemon-services", name="Pokemon Services", version="0.1.3", entry="main.lua"},
  {id="quick-heal-party", name="Quick Heal Party", version="0.1.0", entry="main.lua"},
  {id="summary-ivs", name="Summary IVs", version="0.2.4", entry="main.lua"},
}
